### PR TITLE
Add 02_1_How_to_Write_a_New_Network.ipynb

### PR DESCRIPTION
**Pull request by ikeyasu**
Add https://docs.chainer.org/en/stable/tutorial/convnet.html

notebook https://colab.research.google.com/drive/1d6TTF3eSk9SnMR89OkdmqlAjtMz11s07

### CODE REVIEW

**Comment by keisuke-umezawa** [comment]
@ikeyasu 
Thank you for the contribution. Just one comment.
- It is useless, but you can modify the runtime from cpu to gpu.

**Comment by keisuke-umezawa** [comment]
When running the below codes, the error occured.
I will check error detail.

```
from chainer.links import ResNet152Layers

model = ResNet152Layers()
```

```
Now loading caffemodel (usually it may take few minutes)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-13-9bbbcf043aeb> in <module>()
      1 from chainer.links import ResNet152Layers
      2 
----> 3 model = ResNet152Layers()

/usr/local/lib/python3.6/dist-packages/chainer/links/model/vision/resnet.py in __init__(self, pretrained_model)
    438         if pretrained_model == 'auto':
    439             pretrained_model = 'ResNet-152-model.caffemodel'
--> 440         super(ResNet152Layers, self).__init__(pretrained_model, 152)
    441 
    442 

/usr/local/lib/python3.6/dist-packages/chainer/links/model/vision/resnet.py in __init__(self, pretrained_model, n_layers)
    111         if pretrained_model and pretrained_model.endswith('.caffemodel'):
    112             _retrieve(n_layers, 'ResNet-{}-model.npz'.format(n_layers),
--> 113                       pretrained_model, self)
    114         elif pretrained_model:
    115             npz.load_npz(pretrained_model, self)

/usr/local/lib/python3.6/dist-packages/chainer/links/model/vision/resnet.py in _retrieve(n_layers, name_npz, name_caffemodel, model)
    712     return download.cache_or_load_file(
    713         path, lambda path: _make_npz(path, path_caffemodel, model, n_layers),
--> 714         lambda path: npz.load_npz(path, model))

/usr/local/lib/python3.6/dist-packages/chainer/dataset/download.py in cache_or_load_file(path, creator, loader)
    155 
    156     try:
--> 157         content = creator(temp_path)
    158         with filelock.FileLock(lock_path):
    159             if not os.path.exists(path):

/usr/local/lib/python3.6/dist-packages/chainer/links/model/vision/resnet.py in <lambda>(path)
    711     path_caffemodel = os.path.join(root, name_caffemodel)
    712     return download.cache_or_load_file(
--> 713         path, lambda path: _make_npz(path, path_caffemodel, model, n_layers),
    714         lambda path: npz.load_npz(path, model))

/usr/local/lib/python3.6/dist-packages/chainer/links/model/vision/resnet.py in _make_npz(path_npz, path_caffemodel, model, n_layers)
    699             'The pre-trained caffemodel does not exist. Please download it '
    700             'from \'https://github.com/KaimingHe/deep-residual-networks\', '
--> 701             'and place it on {}'.format(path_caffemodel))
    702 
    703     ResNetLayers.convert_caffemodel_to_npz(path_caffemodel, path_npz, n_layers)

OSError: The pre-trained caffemodel does not exist. Please download it from 'https://github.com/KaimingHe/deep-residual-networks', and place it on /content/.chainer/dataset/pfnet/chainer/models/ResNet-152-model.caffemodel
```

**Comment by ikeyasu** [comment]
@keisuke-umezawa 
Thank you for your comment. I fixed the type to GPU.

Regarding the error, you need to upload 'ResNet-152-model.caffemodel' to root dir of your Google drive. Please refer to [here](https://colab.research.google.com/drive/1d6TTF3eSk9SnMR89OkdmqlAjtMz11s07#scrollTo=XX-M8jirrjv6&line=4&uniqifier=1).

**Comment by keisuke-umezawa** [comment]
@ikeyasu I checked it can run. I will merge it.

**Pull request merged**
